# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iG.ui'
#
# Created: Tue Oct  7 22:37:42 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.currInvGB = QtWidgets.QGroupBox(self.layoutWidget)
        self.currInvGB.setObjectName("currInvGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.currInvGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.currInvNoLabel = QtWidgets.QLabel(self.currInvGB)
        self.currInvNoLabel.setEnabled(True)
        self.currInvNoLabel.setObjectName("currInvNoLabel")
        self.gridLayout.addWidget(self.currInvNoLabel, 0, 0, 1, 1)
        self.currClientLabel = QtWidgets.QLabel(self.currInvGB)
        self.currClientLabel.setObjectName("currClientLabel")
        self.gridLayout.addWidget(self.currClientLabel, 1, 0, 1, 1)
        self.clientsCb = QtWidgets.QComboBox(self.currInvGB)
        self.clientsCb.setObjectName("clientsCb")
        self.gridLayout.addWidget(self.clientsCb, 1, 1, 1, 1)
        self.currInvNo = QtWidgets.QLineEdit(self.currInvGB)
        self.currInvNo.setEnabled(False)
        self.currInvNo.setObjectName("currInvNo")
        self.gridLayout.addWidget(self.currInvNo, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.currInvGB)
        self.previousInvGB = QtWidgets.QGroupBox(self.layoutWidget)
        self.previousInvGB.setObjectName("previousInvGB")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.previousInvGB)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sortByLabel = QtWidgets.QLabel(self.previousInvGB)
        self.sortByLabel.setObjectName("sortByLabel")
        self.gridLayout_2.addWidget(self.sortByLabel, 0, 0, 1, 1)
        self.sortByCb = QtWidgets.QComboBox(self.previousInvGB)
        self.sortByCb.setObjectName("sortByCb")
        self.gridLayout_2.addWidget(self.sortByCb, 0, 1, 1, 1)
        self.invList = QtWidgets.QTreeWidget(self.previousInvGB)
        self.invList.setObjectName("invList")
        self.invList.headerItem().setText(0, "Invoices")
        self.gridLayout_2.addWidget(self.invList, 1, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.previousInvGB)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.previewGB = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.previewGB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.previewGB.setObjectName("previewGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.previewGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.webView = QtWebKitWidgets.QWebView(self.previewGB)
        self.webView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_4.addWidget(self.webView)
        self.verticalLayout_2.addWidget(self.previewGB)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.resetBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_4.addWidget(self.resetBtn)
        self.setCurrentBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.setCurrentBtn.setObjectName("setCurrentBtn")
        self.horizontalLayout_4.addWidget(self.setCurrentBtn)
        self.viewCurrentBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.viewCurrentBtn.setObjectName("viewCurrentBtn")
        self.horizontalLayout_4.addWidget(self.viewCurrentBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_4.addWidget(self.saveBtn)
        self.printBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.printBtn.setObjectName("printBtn")
        self.horizontalLayout_4.addWidget(self.printBtn)
        self.exitBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_4.addWidget(self.exitBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.currInvNoLabel.setBuddy(self.currInvNo)
        self.currClientLabel.setBuddy(self.clientsCb)
        self.sortByLabel.setBuddy(self.sortByCb)

        self.retranslateUi(MainWindow)
        self.actionPreferences.triggered.connect(MainWindow.configurePreferences)
        self.clientsCb.currentTextChanged['QString'].connect(MainWindow.clientChanged)
        self.invList.itemClicked['QTreeWidgetItem*','int'].connect(MainWindow.treeListSelected)
        self.resetBtn.clicked.connect(MainWindow.reset)
        self.setCurrentBtn.clicked.connect(MainWindow.setAsCurrent)
        self.saveBtn.clicked.connect(MainWindow.save)
        self.printBtn.clicked.connect(MainWindow.print)
        self.exitBtn.clicked.connect(MainWindow.close)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionAbout.triggered.connect(MainWindow.about)
        self.sortByCb.currentIndexChanged['int'].connect(MainWindow.sortByOrderChanged)
        self.viewCurrentBtn.clicked.connect(MainWindow.setViewToCurrentInvoice)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currInvNo, self.clientsCb)
        MainWindow.setTabOrder(self.clientsCb, self.sortByCb)
        MainWindow.setTabOrder(self.sortByCb, self.invList)
        MainWindow.setTabOrder(self.invList, self.resetBtn)
        MainWindow.setTabOrder(self.resetBtn, self.setCurrentBtn)
        MainWindow.setTabOrder(self.setCurrentBtn, self.viewCurrentBtn)
        MainWindow.setTabOrder(self.viewCurrentBtn, self.saveBtn)
        MainWindow.setTabOrder(self.saveBtn, self.printBtn)
        MainWindow.setTabOrder(self.printBtn, self.exitBtn)
        MainWindow.setTabOrder(self.exitBtn, self.webView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currInvGB.setTitle(_translate("MainWindow", "Current invoice"))
        self.currInvNoLabel.setText(_translate("MainWindow", "Invoice number"))
        self.currClientLabel.setText(_translate("MainWindow", "Client"))
        self.previousInvGB.setTitle(_translate("MainWindow", "Previous invoices"))
        self.sortByLabel.setText(_translate("MainWindow", "Sort by"))
        self.previewGB.setTitle(_translate("MainWindow", "Preview"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
        self.setCurrentBtn.setText(_translate("MainWindow", "Set as Current"))
        self.viewCurrentBtn.setText(_translate("MainWindow", "View Current"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.printBtn.setText(_translate("MainWindow", "Print"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from PyQt5 import QtWebKitWidgets
