# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lineItemsDialog.ui'
#
# Created: Sat Jul 26 12:43:12 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LineItemsDialog(object):
    def setupUi(self, LineItemsDialog):
        LineItemsDialog.setObjectName("LineItemsDialog")
        LineItemsDialog.resize(739, 397)
        self.gridLayout = QtWidgets.QGridLayout(LineItemsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LineItemsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.note = QtWidgets.QPlainTextEdit(LineItemsDialog)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 0, 1, 1, 5)
        self.label_2 = QtWidgets.QLabel(LineItemsDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(LineItemsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(LineItemsDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(LineItemsDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(LineItemsDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(LineItemsDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 5, 1, 1)
        self.quantity1 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity1.setObjectName("quantity1")
        self.gridLayout.addWidget(self.quantity1, 2, 0, 1, 1)
        self.description1 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description1.setObjectName("description1")
        self.gridLayout.addWidget(self.description1, 2, 1, 1, 1)
        self.price1 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price1.setObjectName("price1")
        self.gridLayout.addWidget(self.price1, 2, 2, 1, 1)
        self.vatCategory1 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory1.setObjectName("vatCategory1")
        self.vatCategory1.addItem("")
        self.vatCategory1.addItem("")
        self.gridLayout.addWidget(self.vatCategory1, 2, 3, 1, 1)
        self.vat1 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat1.setText("")
        self.vat1.setObjectName("vat1")
        self.gridLayout.addWidget(self.vat1, 2, 4, 1, 1)
        self.total1 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total1.setText("")
        self.total1.setObjectName("total1")
        self.gridLayout.addWidget(self.total1, 2, 5, 1, 1)
        self.quantity2 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity2.setObjectName("quantity2")
        self.gridLayout.addWidget(self.quantity2, 3, 0, 1, 1)
        self.description2 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description2.setObjectName("description2")
        self.gridLayout.addWidget(self.description2, 3, 1, 1, 1)
        self.price2 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price2.setObjectName("price2")
        self.gridLayout.addWidget(self.price2, 3, 2, 1, 1)
        self.vatCategory2 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory2.setObjectName("vatCategory2")
        self.vatCategory2.addItem("")
        self.vatCategory2.addItem("")
        self.gridLayout.addWidget(self.vatCategory2, 3, 3, 1, 1)
        self.vat2 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat2.setText("")
        self.vat2.setObjectName("vat2")
        self.gridLayout.addWidget(self.vat2, 3, 4, 1, 1)
        self.total2 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total2.setText("")
        self.total2.setObjectName("total2")
        self.gridLayout.addWidget(self.total2, 3, 5, 1, 1)
        self.quantity3 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity3.setObjectName("quantity3")
        self.gridLayout.addWidget(self.quantity3, 4, 0, 1, 1)
        self.description3 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description3.setObjectName("description3")
        self.gridLayout.addWidget(self.description3, 4, 1, 1, 1)
        self.price3 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price3.setObjectName("price3")
        self.gridLayout.addWidget(self.price3, 4, 2, 1, 1)
        self.vatCategory3 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory3.setObjectName("vatCategory3")
        self.vatCategory3.addItem("")
        self.vatCategory3.addItem("")
        self.gridLayout.addWidget(self.vatCategory3, 4, 3, 1, 1)
        self.vat3 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat3.setText("")
        self.vat3.setObjectName("vat3")
        self.gridLayout.addWidget(self.vat3, 4, 4, 1, 1)
        self.total3 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total3.setText("")
        self.total3.setObjectName("total3")
        self.gridLayout.addWidget(self.total3, 4, 5, 1, 1)
        self.quantity4 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity4.setObjectName("quantity4")
        self.gridLayout.addWidget(self.quantity4, 5, 0, 1, 1)
        self.description4 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description4.setObjectName("description4")
        self.gridLayout.addWidget(self.description4, 5, 1, 1, 1)
        self.price4 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price4.setObjectName("price4")
        self.gridLayout.addWidget(self.price4, 5, 2, 1, 1)
        self.vatCategory4 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory4.setObjectName("vatCategory4")
        self.vatCategory4.addItem("")
        self.vatCategory4.addItem("")
        self.gridLayout.addWidget(self.vatCategory4, 5, 3, 1, 1)
        self.vat4 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat4.setText("")
        self.vat4.setObjectName("vat4")
        self.gridLayout.addWidget(self.vat4, 5, 4, 1, 1)
        self.total4 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total4.setText("")
        self.total4.setObjectName("total4")
        self.gridLayout.addWidget(self.total4, 5, 5, 1, 1)
        self.quantity5 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity5.setObjectName("quantity5")
        self.gridLayout.addWidget(self.quantity5, 6, 0, 1, 1)
        self.description5 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description5.setObjectName("description5")
        self.gridLayout.addWidget(self.description5, 6, 1, 1, 1)
        self.price5 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price5.setObjectName("price5")
        self.gridLayout.addWidget(self.price5, 6, 2, 1, 1)
        self.vatCategory5 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory5.setObjectName("vatCategory5")
        self.vatCategory5.addItem("")
        self.vatCategory5.addItem("")
        self.gridLayout.addWidget(self.vatCategory5, 6, 3, 1, 1)
        self.vat5 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat5.setText("")
        self.vat5.setObjectName("vat5")
        self.gridLayout.addWidget(self.vat5, 6, 4, 1, 1)
        self.total5 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total5.setText("")
        self.total5.setObjectName("total5")
        self.gridLayout.addWidget(self.total5, 6, 5, 1, 1)
        self.quantity6 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity6.setObjectName("quantity6")
        self.gridLayout.addWidget(self.quantity6, 7, 0, 1, 1)
        self.description6 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description6.setObjectName("description6")
        self.gridLayout.addWidget(self.description6, 7, 1, 1, 1)
        self.price6 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price6.setObjectName("price6")
        self.gridLayout.addWidget(self.price6, 7, 2, 1, 1)
        self.vatCategory6 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory6.setObjectName("vatCategory6")
        self.vatCategory6.addItem("")
        self.vatCategory6.addItem("")
        self.gridLayout.addWidget(self.vatCategory6, 7, 3, 1, 1)
        self.vat6 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat6.setText("")
        self.vat6.setObjectName("vat6")
        self.gridLayout.addWidget(self.vat6, 7, 4, 1, 1)
        self.total6 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total6.setText("")
        self.total6.setObjectName("total6")
        self.gridLayout.addWidget(self.total6, 7, 5, 1, 1)
        self.quantity7 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity7.setObjectName("quantity7")
        self.gridLayout.addWidget(self.quantity7, 8, 0, 1, 1)
        self.description7 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description7.setObjectName("description7")
        self.gridLayout.addWidget(self.description7, 8, 1, 1, 1)
        self.price7 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price7.setObjectName("price7")
        self.gridLayout.addWidget(self.price7, 8, 2, 1, 1)
        self.vatCategory7 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory7.setObjectName("vatCategory7")
        self.vatCategory7.addItem("")
        self.vatCategory7.addItem("")
        self.gridLayout.addWidget(self.vatCategory7, 8, 3, 1, 1)
        self.vat7 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat7.setText("")
        self.vat7.setObjectName("vat7")
        self.gridLayout.addWidget(self.vat7, 8, 4, 1, 1)
        self.total7 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total7.setText("")
        self.total7.setObjectName("total7")
        self.gridLayout.addWidget(self.total7, 8, 5, 1, 1)
        self.quantity8 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity8.setObjectName("quantity8")
        self.gridLayout.addWidget(self.quantity8, 9, 0, 1, 1)
        self.description8 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description8.setObjectName("description8")
        self.gridLayout.addWidget(self.description8, 9, 1, 1, 1)
        self.price8 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price8.setObjectName("price8")
        self.gridLayout.addWidget(self.price8, 9, 2, 1, 1)
        self.vatCategory8 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory8.setObjectName("vatCategory8")
        self.vatCategory8.addItem("")
        self.vatCategory8.addItem("")
        self.gridLayout.addWidget(self.vatCategory8, 9, 3, 1, 1)
        self.vat8 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat8.setText("")
        self.vat8.setObjectName("vat8")
        self.gridLayout.addWidget(self.vat8, 9, 4, 1, 1)
        self.total8 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total8.setText("")
        self.total8.setObjectName("total8")
        self.gridLayout.addWidget(self.total8, 9, 5, 1, 1)
        self.quantity9 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity9.setObjectName("quantity9")
        self.gridLayout.addWidget(self.quantity9, 10, 0, 1, 1)
        self.description9 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description9.setObjectName("description9")
        self.gridLayout.addWidget(self.description9, 10, 1, 1, 1)
        self.price9 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price9.setObjectName("price9")
        self.gridLayout.addWidget(self.price9, 10, 2, 1, 1)
        self.vatCategory9 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory9.setObjectName("vatCategory9")
        self.vatCategory9.addItem("")
        self.vatCategory9.addItem("")
        self.gridLayout.addWidget(self.vatCategory9, 10, 3, 1, 1)
        self.vat9 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat9.setText("")
        self.vat9.setObjectName("vat9")
        self.gridLayout.addWidget(self.vat9, 10, 4, 1, 1)
        self.total9 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total9.setText("")
        self.total9.setObjectName("total9")
        self.gridLayout.addWidget(self.total9, 10, 5, 1, 1)
        self.quantity10 = QtWidgets.QLineEdit(LineItemsDialog)
        self.quantity10.setObjectName("quantity10")
        self.gridLayout.addWidget(self.quantity10, 11, 0, 1, 1)
        self.description10 = QtWidgets.QLineEdit(LineItemsDialog)
        self.description10.setObjectName("description10")
        self.gridLayout.addWidget(self.description10, 11, 1, 1, 1)
        self.price10 = QtWidgets.QLineEdit(LineItemsDialog)
        self.price10.setObjectName("price10")
        self.gridLayout.addWidget(self.price10, 11, 2, 1, 1)
        self.vatCategory10 = QtWidgets.QComboBox(LineItemsDialog)
        self.vatCategory10.setObjectName("vatCategory10")
        self.vatCategory10.addItem("")
        self.vatCategory10.addItem("")
        self.gridLayout.addWidget(self.vatCategory10, 11, 3, 1, 1)
        self.vat10 = QtWidgets.QLineEdit(LineItemsDialog)
        self.vat10.setText("")
        self.vat10.setObjectName("vat10")
        self.gridLayout.addWidget(self.vat10, 11, 4, 1, 1)
        self.total10 = QtWidgets.QLineEdit(LineItemsDialog)
        self.total10.setText("")
        self.total10.setObjectName("total10")
        self.gridLayout.addWidget(self.total10, 11, 5, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(LineItemsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 12, 5, 1, 1)

        self.retranslateUi(LineItemsDialog)
        self.buttonBox.accepted.connect(LineItemsDialog.accept)
        self.buttonBox.rejected.connect(LineItemsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LineItemsDialog)

    def retranslateUi(self, LineItemsDialog):
        _translate = QtCore.QCoreApplication.translate
        LineItemsDialog.setWindowTitle(_translate("LineItemsDialog", "Line items"))
        self.label.setText(_translate("LineItemsDialog", "Note"))
        self.label_2.setText(_translate("LineItemsDialog", "Quantity"))
        self.label_3.setText(_translate("LineItemsDialog", "Description"))
        self.label_4.setText(_translate("LineItemsDialog", "Price"))
        self.label_5.setText(_translate("LineItemsDialog", "Tax Rate"))
        self.label_7.setText(_translate("LineItemsDialog", "Vat"))
        self.label_6.setText(_translate("LineItemsDialog", "Total"))
        self.vatCategory1.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory1.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory2.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory2.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory3.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory3.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory4.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory4.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory5.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory5.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory6.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory6.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory7.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory7.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory8.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory8.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory9.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory9.setItemText(1, _translate("LineItemsDialog", "19%"))
        self.vatCategory10.setItemText(0, _translate("LineItemsDialog", "7%"))
        self.vatCategory10.setItemText(1, _translate("LineItemsDialog", "19%"))

